force-app/main/default/objects/Case/fields/Canal_d_achat__c.field-meta.xml
<CustomField>
    <fullName>Canal_d_achat__c</fullName>
    <label>Canal d&apos;achat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boutique</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Héritage</fullName>
            </value>
            <value>
                <fullName>Seconde main</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande information</fullName>
            </value>
            <value>
                <fullName>Echange produit</fullName>
            </value>
            <value>
                <fullName>Réclamation</fullName>
            </value>
            <value>
                <fullName>Retour produit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Client_segment__c.field-meta.xml
<CustomField>
    <fullName>Client_segment__c</fullName>
    <label>Client segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Date_d_achat__c.field-meta.xml
<CustomField>
    <fullName>Date_d_achat__c</fullName>
    <label>Date d&apos;achat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_number__c.field-meta.xml
<CustomField>
    <fullName>Order_number__c</fullName>
    <label>Order number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Produit__c.field-meta.xml
<CustomField>
    <fullName>Produit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Cases (Produit)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponibilité produit</fullName>
            </value>
            <value>
                <fullName>Suivi commande</fullName>
            </value>
            <value>
                <fullName>Information sur prix / promotion</fullName>
            </value>
            <value>
                <fullName>Informations sur personnalisation</fullName>
            </value>
            <value>
                <fullName>Taille / ajustement</fullName>
            </value>
            <value>
                <fullName>Couleur / modèle</fullName>
            </value>
            <value>
                <fullName>Produit défectueux</fullName>
            </value>
            <value>
                <fullName>Produit non conforme à la commande</fullName>
            </value>
            <value>
                <fullName>Produit endommagé / défectueux</fullName>
            </value>
            <value>
                <fullName>Livraison retardée</fullName>
            </value>
            <value>
                <fullName>Erreur de facturation</fullName>
            </value>
            <value>
                <fullName>Mauvais produit livré</fullName>
            </value>
            <value>
                <fullName>Remboursement demandé</fullName>
            </value>
            <value>
                <fullName>Retour pour non-conformité</fullName>
            </value>
            <value>
                <fullName>Comment faire un retour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Client_segment__c.field-meta.xml
<CustomField>
    <fullName>Client_segment__c</fullName>
    <label>Client segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Produit Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.history/force-app/main/default/classes/CaseManagement/Controller/SavCaseController/SavCaseController_20260402145349.cls
public without sharing class SavCaseController {

    @AuraEnabled
    public static String createCase(Map<String, String> caseDetails) {
        try {
            // 1. Récupération de l'utilisateur
            User currentUser = [SELECT ContactId, Contact.Client_segment__c 
                                FROM User 
                                WHERE Id = :UserInfo.getUserId() 
                                LIMIT 1];
            
            // 2. Création de la requête
            Case newCase = new Case();
            newCase.Subject = caseDetails.get('subject');
            newCase.Description = caseDetails.get('description');
            newCase.Category__c = caseDetails.get('category'); 
            newCase.Subcategory__c = caseDetails.get('subcategory');
            newCase.Order_number__c = caseDetails.get('orderNumber'); // Champ Numéro de commande
            newCase.Origin = 'Web';
            newCase.ContactId = currentUser.ContactId;
            
            newCase.Client_segment__c = currentUser.Contact.Client_segment__c;
            newCase.Priority = (newCase.Client_segment__c == 'VIP') ? 'High' : 'Medium';

            if(String.isNotBlank(caseDetails.get('purchaseDate'))) {
                newCase.Date_d_achat__c = Date.valueOf(caseDetails.get('purchaseDate'));
            }
            newCase.Canal_d_achat__c = caseDetails.get('channel');
            newCase.Produit__c = caseDetails.get('productId');

            // Règle d'assignation
            List<AssignmentRule> arList = [SELECT Id FROM AssignmentRule WHERE SobjectType = 'Case' AND Active = true LIMIT 1];
            if (!arList.isEmpty()) {
                Database.DMLOptions dmlOpts = new Database.DMLOptions();
                dmlOpts.assignmentRuleHeader.assignmentRuleId = arList[0].Id;
                newCase.setOptions(dmlOpts);
            }

            insert newCase;
            return newCase.Id;
            
        } catch (Exception e) {
            throw new AuraHandledException('Erreur : ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Product__c> getMyProducts() {
        // Retour à la version initiale qui affiche les produits de l'objet personnalisé
        return [SELECT Id, Name FROM Product__c LIMIT 50];
    }
}