force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande information</fullName>
            </value>
            <value>
                <fullName>Echange produit</fullName>
            </value>
            <value>
                <fullName>Réclamation</fullName>
            </value>
            <value>
                <fullName>Retour produit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponibilité produit</fullName>
            </value>
            <value>
                <fullName>Suivi commande</fullName>
            </value>
            <value>
                <fullName>Information sur prix / promotion</fullName>
            </value>
            <value>
                <fullName>Informations sur personnalisation</fullName>
            </value>
            <value>
                <fullName>Taille / ajustement</fullName>
            </value>
            <value>
                <fullName>Couleur / modèle</fullName>
            </value>
            <value>
                <fullName>Produit défectueux</fullName>
            </value>
            <value>
                <fullName>Produit non conforme à la commande</fullName>
            </value>
            <value>
                <fullName>Produit endommagé / défectueux</fullName>
            </value>
            <value>
                <fullName>Livraison retardée</fullName>
            </value>
            <value>
                <fullName>Erreur de facturation</fullName>
            </value>
            <value>
                <fullName>Mauvais produit livré</fullName>
            </value>
            <value>
                <fullName>Remboursement demandé</fullName>
            </value>
            <value>
                <fullName>Retour pour non-conformité</fullName>
            </value>
            <value>
                <fullName>Comment faire un retour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTrainingBatch.cls
global class CaseTrainingBatch implements Database.Batchable<Integer> {

    Map<String, List<String>> mapping = new Map<String, List<String>>{
        'Demande information' => new List<String>{
            'Disponibilité produit',
            'Suivi commande',
            'Information sur prix / promotion',
            'Informations sur personnalisation',
            'Comment faire un retour'
        },
        'Echange produit' => new List<String>{
            'Taille / ajustement',
            'Couleur / modèle',
            'Produit défectueux',
            'Produit non conforme à la commande'
        },
        'Réclamation' => new List<String>{
            'Produit endommagé / défectueux',
            'Livraison retardée',
            'Erreur de facturation',
            'Mauvais produit livré'
        },
        'Retour produit' => new List<String>{
            'Remboursement demandé',
            'Retour pour non-conformité'
        }
    };

    List<String> priorities = new List<String>{'Low', 'Medium', 'High'};

    global Iterable<Integer> start(Database.BatchableContext bc) {
        List<Integer> scope = new List<Integer>();
        for (Integer i = 0; i < 400; i++) {
            scope.add(i);
        }
        return scope;
    }

    global void execute(Database.BatchableContext bc, List<Integer> scope) {

        List<Case> casesToInsert = new List<Case>();

        for (Integer i : scope) {

            List<String> categories = new List<String>(mapping.keySet());
            String category = categories[(Integer)(Math.random() * categories.size())];

            List<String> subCats = mapping.get(category);
            String subCat = subCats[(Integer)(Math.random() * subCats.size())];

            String priority = priorities[(Integer)(Math.random() * priorities.size())];

            casesToInsert.add(new Case(
                Subject = 'Einstein Training #' + i + ' : ' + category + ' - ' + subCat,
                Description = 'Dataset auto classification - ' + subCat,
                Status = 'Closed',
                Origin = 'Web',
                Priority = priority,
                Category__c = category,
                Subcategory__c = subCat
            ));
        }

        insert casesToInsert;
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('Batch terminé : 400 cases créés pour Einstein training.');
    }
}